Row group statistics
segmentio/parquet-go pull request #485
Opened 2023-03-16 19:27 UTC by suremarc

See #410. This PR adds row group statistics, which will enable row-group level predicate pushdown. 

The tests mostly pass with the changes I added, only that the column encodings seem to have a nondeterministic order. I had to build `parquet-tools` from scratch, so I'm not sure if this was just me building the wrong version or something.

2023-03-28 23:42 UTC, bartleyg requested changes
Thanks for the contribution! These tests aren't hooked up in Github Actions b/c no parquet-writer is installed so I had to run them locally. I saw your note about non-deterministic encoding order. Since I can only verify locally for these, if you make the suggested changes I can merge this in!

2023-03-31 16:27 UTC, suremarc commented
> Thanks for the contribution! These tests aren't hooked up in Github Actions b/c no parquet-writer is installed so I had to run them locally. I saw your note about non-deterministic encoding order. Since I can only verify locally for these, if you make the suggested changes I can merge this in!

Thanks! I made the requested changes. LMK if anything still looks off.

2023-03-31 19:09 UTC, bartleyg requested changes

2023-03-31 19:09 UTC, bartleyg commented on writer_test.go
> +name:   name:   BINARY UNCOMPRESSED DO:4 FPO:49 SZ:73/73/1.00 VC:2 ENC:RLE_DICTIONARY,PLAIN ST:[min: customer1, max: customer2, num_nulls not defined]
there's an extra name: prepended there but this suggestion should work below:
```suggestion
name:   BINARY UNCOMPRESSED DO:4 FPO:49 SZ:73/73/1.00 VC:2 ENC:RLE_DICTIONARY,PLAIN ST:[min: customer1, max: customer2, num_nulls not defined]
```

2023-04-03 20:20 UTC, bartleyg approved these changes

2023-04-03 20:20 UTC, merged